### ISSUE TITLE
No callback called with encrypt

### ISSUE THREAD

**Issue by chi-mai2b** [disusered/cordova-safe#8]
Neither of the callbacks provided to `safe.encrypt` are getting called.

**Info:**

	OS: Windows 7
	Device:
		OnePlus One
		Android version: 5.0.2

	$ cordova --version
		5.1.1
	$ cordova plugins list
		cordova-plugin-file 2.1.0 "File"
		cordova-plugin-whitelist 1.0.0 "Whitelist"
		cordova-safe 1.1.1 "Safe"

Code to reproduce the issue:

	var
	    onDeviceReady = function () {
            // create a file in the persistent storage
	        window.requestFileSystem(window.PERSISTENT, 5 * 1024 * 1024, onInitFs, onError);
	    },
	    onError = function (e) {
	        console.error('Error:', e, e.code);
	    },
	    onInitFs = function (fs) {
	        console.log('Opened file system: ' + fs.name);

	        fs.root.getFile('userData.json', {create: true, exclusive: false}, function (fileEntry) {
	            fileEntry.createWriter(function (fileWriter) {
	                fileWriter.onwriteend = onFileWriteComplete;
	                fileWriter.onerror = onError;

	                // Write a file containing some test data
	                fileWriter.write(new Blob(
	                        [JSON.stringify({some: 'data'})],
	                        {type: 'application/json'})
	                );
	            }, onError);
	        }, onError);
	    },
	    onFileWriteComplete = function (file) {
	        // here the file should be created and available on the device
	        var safe = cordova.plugins.disusered.safe,
	            key = 'someKey',
	            onEncryptSuccess = function (encryptedFile) {
	                console.log('Encrypted file: ' + encryptedFile);
	            };
	        // file.target.localURL value is "cdvfile://localhost/persistent/userData.json"
	        safe.encrypt(file.target.localURL, key, onEncryptSuccess, onError);
	    };

	document.addEventListener('deviceready', onDeviceReady, false);

In the code above `onEncryptSuccess` or `onError` should be called.
The function `onFileWriteComplete` is called and the file exists on the device with the rights: `-rw-rw----`.

**Comment by disusered** [comment]
Sorry about that and thanks for the sample code, I'm taking a look.

**Comment by disusered** [comment]
On a stock device and cordova install on 5.0 with your sample code I get:

`/persistent/userData.json: open failed: ENOENT (No such file or directory)`

Cordova's Android [file system layout](https://github.com/apache/cordova-plugin-file#android-file-system-layout)  is much more complex than the Java implementation. This is also a reason for #7. I'm working on it but it will probably be another day or two!

**Comment by disusered** [comment]
This seems to be an issue with <cdvfile> convention introduced in 3.x. Thanks much for the debug information, it was super helpful! Your example code is now running as-is, I pushed the update a few minutes ago so let me know if it works.

References:
- CB-6051: Android: Allow media plugin to handle invalid file locations [[1]](https://issues.apache.org/jira/browse/CB-6051) [[2]](https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-media.git;a=blobdiff;f=src/android/AudioHandler.java;h=45e683778040f3f8b2171342c0012823864e2247;hp=40f7ea910e01913e36b0ea26e56435b9e1551274;hb=b365d09;hpb=f96f2ac8cadfecf390a736fb94fe146b9bb0d4d8) [[3]](https://git-wip-us.apache.org/repos/asf?p=cordova-plugin-media.git;a=blobdiff;f=src/android/AudioHandler.java;h=40f7ea910e01913e36b0ea26e56435b9e1551274;hp=63d8580c002fad02e9ca489d7bbd7beb6269a2aa;hb=f96f2ac;hpb=63801287ca03a7d54f41341e4b4ea19a2ec1a9bf)
- Converting cdvfile:// URLs to fileystem paths [[1]](http://docs.monaca.mobi/3.5/en/reference/phonegap_34/en/file/plugins/)
- cordova-plugin-file [[1]](https://github.com/apache/cordova-plugin-file#android-file-system-layout)

**Comment by marc-ed-raffalli** [comment]
Glad it helped, thanks a lot for the fix :)
Just tried on the device, it seems all good.

**Comment by disusered** [comment]
Awesome, great to hear!

**Comment by manojbhardwaj** [comment]
plugin is not working in ionic 3 already installed but still showing i have to installed the plugin
